# Quick-jump bookmarks
[[mgr.prepend_keymap]]
on = ["g", "c"]
run = "cd ~/Code"
desc = "Go to ~/Code"

[[mgr.prepend_keymap]]
on = ["g", "d"]
run = "cd ~/Downloads"
desc = "Go to ~/Downloads"

[[mgr.prepend_keymap]]
on = ["g", "."]
run = "cd ~/.config"
desc = "Go to ~/.config"

# chmod plugin
[[mgr.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "chmod on selected file(s)"
