k9s:
  liveViewAutoRefresh: false
  gpuVendors: {}
  screenDumpDir: /Users/vincent/.local/state/k9s/screen-dumps
  refreshRate: 2
  apiServerTimeout: 2m0s
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  portForwardAddress: localhost
  ui:
    enableMouse: true
    headless: true
    logoless: true
    crumbsless: true
    splashless: true
    reactive: true
    noIcons: false
    invert: false
    defaultsToFullScreen: false
    useFullGVRTitle: false
    skin: catppuccin-mocha-transparent
  skipLatestRevCheck: true
  disablePodCounting: false
  shellPod:
    image: busybox:1.37.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 500
    buffer: 5000
    sinceSeconds: -1
    textWrap: true
    disableAutoscroll: false
    columnLock: false
    showTime: true
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  defaultView: ""
